### ISSUE TITLE
unable to access req.body

### ISSUE THREAD

**Issue by subodh2508** [Threadster/express-joi-validator#6]
Hello sir,
 i am quite newbie to node js. Please help me to resolve the issue.

i am using multer npm for accessing multipart/form-data, but now i want to validate form-data for that i am using express-joi-validator npm but it is not possible to validate form-data.

sample of code mention below: 
-------------------------------------------------------------------------------------------
var bodyParser = require('body-parser');
var app = express();
var multer  = require('multer');
var ExpressJoi = require('express-joi-validator');
var Joi = require('joi');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

var storage =   multer.diskStorage({  
  destination: function (req, file, callback) { 
    callback(null, './uploads');  
  },  
  filename: function (req, file, callback) {  
	var filename = (file.originalname).split(".");
	filename[0] = filename[0] + '_' + Date.now();
	var fname = filename.join(".");
    callback(null, fname);
  }  
});  
var upload = multer({ storage : storage});

var bodySchema = {
    body: {
                name: Joi.string().alphanum().min(3).max(30),//.required(),
		age: Joi.number().integer().positive().greater(15).required(),
		image: Joi.required()
    }
};

app.post('/employee',ExpressJoi(bodySchema), function(req, res){
	profilePicUpload(req, res, function (err) {
		var flag = 0;
		var format;
		console.log("body >> ");
		console.log(req.body);  // getting {}
		
  });
});

---------------------------------------------------------------------------------------
Error: 
Error: child "body" fails because [child "age" fails because ["age" is required]]
    at Object.exports.create (D:\Subodh\node_modules\express-joi-validator\node_modules\boom\lib\index.js:21:17)
    at Object.exports.badRequest (D:\Subodh\node_modules\express-joi-validator\node_modules\boom\lib\index.js:79:20)
    at onValidationComplete (D:\Subodh\node_modules\express-joi-validator\index.js:28:26)
    at internals.Any._validateWithOptions (D:\Subodh\node_modules\express-joi-validator\node_modules\joi\lib\any.js:657:16)
    at root.validate (D:\Subodh\node_modules\express-joi-validator\node_modules\joi\lib\index.js:100:23)
    at validateRequest (D:\Subodh\node_modules\express-joi-validator\index.js:24:16)
    at Layer.handle [as handle_request] (D:\Subodh\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Subodh\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\Subodh\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Subodh\node_modules\express\lib\router\layer.js:95:5)

Please look into it.
Waiting for the response.

Thanks and Regards,
Subodh

**Comment by viztastic** [comment]
I am experiencing the same issue.
